// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -source=types.go -package=checker --destination=mock_test.go
//

// Package checker is a generated GoMock package.
package checker

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockrecorder is a mock of recorder interface.
type Mockrecorder struct {
	ctrl     *gomock.Controller
	recorder *MockrecorderMockRecorder
	isgomock struct{}
}

// MockrecorderMockRecorder is the mock recorder for Mockrecorder.
type MockrecorderMockRecorder struct {
	mock *Mockrecorder
}

// NewMockrecorder creates a new mock instance.
func NewMockrecorder(ctrl *gomock.Controller) *Mockrecorder {
	mock := &Mockrecorder{ctrl: ctrl}
	mock.recorder = &MockrecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrecorder) EXPECT() *MockrecorderMockRecorder {
	return m.recorder
}

// RecordUsage mocks base method.
func (m *Mockrecorder) RecordUsage(frm, to string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordUsage", frm, to)
}

// RecordUsage indicates an expected call of RecordUsage.
func (mr *MockrecorderMockRecorder) RecordUsage(frm, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordUsage", reflect.TypeOf((*Mockrecorder)(nil).RecordUsage), frm, to)
}
