version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "05:00"
      timezone: "Asia/Tokyo"
    groups:
      go-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "05:00"
      timezone: "Asia/Tokyo"
    groups:
      github-actions:
        patterns:
          - "*"
