---
# Use the same content with json to make code management easy.
{
  "targetPackagePrefixList": [
    "github.com/cloverrose/pkgdep/example"
  ],
  "isExcludeTests": true,
  "enableRegexp": true,
  "dependencies": {
    "github.com/cloverrose/pkgdep/example/infra": [
      "github.com/cloverrose/pkgdep/example/domain/.*$"
    ],
    "github.com/cloverrose/pkgdep/example/service": [
      "github.com/cloverrose/pkgdep/example/domain/.*$",
      "github.com/cloverrose/pkgdep/example/infra"
    ],
    "github.com/cloverrose/pkgdep/example/application": [
      "github.com/cloverrose/pkgdep/example/service"
    ],
    "github.com/cloverrose/pkgdep/example/foundations/(?P<foundationName>[^/]+)/service": [
      "github.com/cloverrose/pkgdep/example/foundations/{{.foundationName}}/(domain|infra)"
    ]
  }
}
